import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import { Item } from '../types';

const inter = Inter({ subsets: ['latin'] });
const langArr:string[]=["ALL","HTML","CSS","JAVASCRIPT"];

const getData=async(tech:string)=>{
      let res=await fetch(`https://api.github.com/search/repositories?q=stars:%3E1+language:${tech}`);
      let data=res.json();
      return data;
}

export default function Home() {
  const[active,setActive]=useState(0);
  const[data,setData]=useState([]);

  const[loading,setLoading]=useState(false);

  const validateData=async (active:number)=>{
    try {
      setLoading(true);
    let tech=langArr[active].toString();
    let data=await getData(tech);
    setData(data.items);
    setLoading(false);
    } catch (error) {
      setLoading(false);
    }
  } 

  const handleLang=(ind:number)=>{
    setActive(ind);
  }

  console.log(data)

 useEffect(()=>{
    validateData(active);
 },[active])

  // console.log(langArr[active].toLowerCase());

  if(loading){
    return<h1 style={{"textAlign":"center"}}>Loading...</h1>
  }



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.nav}>
          {
            langArr?.map((lang:string,ind:number) =><p key={ind} style={ind===active?{"backgroundColor":"red"}:null} onClick={()=>handleLang(ind)}>{lang}</p>)
          }
      </div>
      <div className={styles.repos}>
          {
            data?.map((repo:Item)=><div key={repo.id}>
              <img src={repo.owner.avatar_url} alt={repo.name} />
              <h2>{repo.name}</h2>
              <p>Language:- {repo.language?repo.language:"None"}</p>
              <p>Fork Counts :- {repo.forks_count}</p>
              <p>Star Count :- {repo.stargazers_count}</p>
            </div>)
          }
      </div>
    </>
  )
}
